// TEMPLATE — multi-page run site builder. Copy to runs/<slug>/, fill CONFIG and
// PAGES, then: node build_site.js
//
// Why a builder rather than five hand-written files: head, nav and footer live in
// one shell, so pages cannot drift apart and adding a page is one array entry.
// Pair with templates/site.css (copy alongside; every page links it).
const fs = require('fs');

// ─── CONFIG — the only brand-specific block ──────────────────────────────────
const CONFIG = {
  brand: 'Understudy',
  accent: '#4338CA',
  ink: '#0B0B12',
  heroImage: 'visuals/hero/hero.svg',
  repo: 'https://github.com/dlmastery/startup-skills',
  disclosure: '<strong>Understudy</strong> is a founder-artifact pack generated by an artifact pipeline — '
    + 'not a funded company, not a shipping product, and not a company with customers. '
    + '<strong>There is no traction: no pilot, no customer, no code.</strong> Every operating figure on this site is a '
    + 'declared target carrying its source or an (assumption) tag, and the pack states where each would be falsified. '
    + 'Row-by-row completeness is in audit/COVERAGE.md.',
};

// Standard page set. Home routes; each interior page does exactly one job.
const NAV = [
  { slug: 'index',    label: 'Home' },
  { slug: 'product',  label: 'Product' },
  { slug: 'evidence', label: 'Evidence' },
  { slug: 'pricing',  label: 'Pricing' },
  { slug: 'about',    label: 'About' },
  { slug: 'visuals',  label: 'Visuals' },
];

const LOGO = `<svg viewBox="0 0 100 100" aria-hidden="true"><rect width="100" height="100" rx="22" fill="${CONFIG.ink}"/>`
  + `<path d="M20 74 L38 52 L54 62 L80 26" stroke="${CONFIG.accent}" stroke-width="10" fill="none" stroke-linejoin="round" stroke-linecap="round"/></svg>`;

const shell = (page) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<title>${page.title}</title>
<meta name="description" content="${page.desc}">
<meta property="og:title" content="${page.title}">
<meta property="og:description" content="${page.desc}">
<meta property="og:type" content="website">
<meta property="og:image" content="${CONFIG.heroImage}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="site.css">
</head>
<body>

<nav class="site">
  <div class="w">
    <a class="brand" href="index.html">${LOGO} ${CONFIG.brand}</a>
    <div class="nl">
      ${NAV.filter(n => n.slug !== 'index').map(n =>
        `<a href="${n.slug}.html"${n.slug === page.slug ? ' class="on"' : ''}>${n.label}</a>`).join('\n      ')}
      <a href="pack.html">The pack</a>
    </div>
    <a class="btn" href="pack.html">Read the pack</a>
  </div>
</nav>

${page.body}

<div class="next">
  <div class="w">
    <span class="eyebrow">Keep reading</span>
    <div class="row">
      ${page.next.map(n => `<a href="${n.href}"><div class="k">${n.k}</div><div class="t">${n.t}</div><div class="d">${n.d}</div></a>`).join('\n      ')}
    </div>
  </div>
</div>

<footer>
  <div class="w">
    <div class="fl">
      ${NAV.map(n => `<a href="${n.slug}.html">${n.label}</a>`).join('')}<a href="pack.html">The pack</a>
      <a href="${CONFIG.repo}">GitHub</a>
    </div>
    <p class="fine">${CONFIG.disclosure}</p>
  </div>
</footer>
</body>
</html>
`;

// ─── PAGES ───────────────────────────────────────────────────────────────────
// Home follows the researched anatomy in startup-website's SKILL.md, in this
// order, and does not get reordered to be clever:
//   hero (OUTCOME headline + who it is for + ONE cta + visual)
//   -> proof strip (within the first two scrolls)
//   -> why this exists (the problem in human terms, no jargon, no product yet)
//   -> how it works (three steps + the one rule)
//   -> who it is for  -> what you actually get
//   -> why you should believe it   <-- domain vocabulary is earned HERE, not before
//   -> get started
const PAGES = [
  { slug: 'index', title: 'Understudy — the service desk that learns your client environments',
    desc: 'Understudy records IT engineers working and clusters those recordings into an executable skill library. For MSPs, where onboarding a client environment is cost of goods.',
    next: [
      { href: 'product.html', k: 'Product', t: 'How it works', d: 'Watch, distil, rehearse, gate, act, verify — and why supervision is architecture, not a phase.' },
      { href: 'evidence.html', k: 'Evidence', t: 'What we actually know', d: 'Every assumption untested, and the four that would kill the company.' },
      { href: 'pack.html', k: 'The pack', t: 'All 70 documents', d: 'Research, strategy, product, tech, narrative, validation and financials.' }],
    body: `
<header class="hero"><div class="w">
  <span class="eyebrow">For MSPs</span>
  <h1>Understudy helps MSPs onboard a client environment in <span class="hl">21 engineer-hours instead of 25&ndash;40</span> &mdash; from the second client onward.</h1>
  <p class="lede">It records your engineers working &mdash; screen, actions, and ten seconds of spoken reasoning at the moments that matter &mdash; then clusters those recordings into a readable, executable skill library. Every AI service desk can resolve a ticket. None of them can learn where it is.</p>
  <a class="btn lg" href="product.html">See how it works</a>
  <a class="btn ghost lg" href="pack.html">Read the pack</a>
  <img class="heroimg" src="visuals/hero/hero.svg" alt="Watch, distil, rehearse, gate and act">
</div></header>

<section class="strip"><div class="w"><div class="row">
  <div><div class="k">25&ndash;40 hrs</div><div class="d">to onboard a median client today <span class="src">[S21]</span></div></div>
  <div><div class="k">26%</div><div class="d">of MSPs cannot staff clients they could win <span class="src">[S33]</span></div></div>
  <div><div class="k">41</div><div class="d">environments a single MSP customer brings</div></div>
  <div><div class="k">0</div><div class="d">customers. This is a pre-build pack, and says so</div></div>
</div></div></section>

<section><div class="w narrow">
  <span class="eyebrow">Why this exists</span>
  <h2>The knowledge that would make automation work is performed every day and captured nowhere.</h2>
  <p>An MSP takes on a new client. Somebody spends three weeks learning how that client&rsquo;s systems are wired &mdash; which policies are unusual, what breaks, how you know it worked &mdash; and most of it ends up in one person&rsquo;s head. Then it happens again with the next client. And when that person leaves, it happens again with the same client.</p>
  <p>It is not a documentation problem. Writing it down is a separate act from doing the work, so it competes with billable hours and loses. <strong>Understudy exists because those two acts can now be the same act.</strong></p>
</div></section>

<section class="alt"><div class="w">
  <span class="eyebrow">How it works</span>
  <h2>Three steps, and one rule that makes it different.</h2>
  <div class="cards3">
    <div class="card"><div class="n">01</div><h3>Watch</h3><p>Passive capture across the tools your engineers actually use &mdash; RMM consoles, directory, terminals, MDM. Credentials are dropped at capture, before storage. Narration is prompted only at decision points, ten seconds at a time.</p></div>
    <div class="card"><div class="n">02</div><h3>Distil</h3><p>Recordings of the same procedure cluster into one readable <code>SKILL.md</code> &mdash; goal, preconditions, steps, and a test for what &ldquo;done correctly&rdquo; means. Your engineers read it, correct it, and can reject it outright.</p></div>
    <div class="card"><div class="n">03</div><h3>Act</h3><p>Skills run in shadow first, then behind approval gates. Every action is checked against its success criterion, under the agent&rsquo;s own identity in your client&rsquo;s audit log.</p></div>
  </div>
  <div class="rule"><strong>The rule:</strong> destructive actions are always gated, and that is not configurable. Long-horizon agent completion sits at 20.6% <span class="src">[S16]</span>, so supervision here is architecture &mdash; not a phase we plan to remove.</div>
</div></section>

<section><div class="w">
  <span class="eyebrow">Who it is for</span>
  <h2>Three people, one system, no separate tiers.</h2>
  <div class="cards3">
    <div class="card"><h3>The tier-1 technician</h3><p>Gets this client&rsquo;s procedure where there was a generic runbook &mdash; including the two ways this tenant differs from every other one.</p></div>
    <div class="card"><h3>The delivery manager</h3><p>Stops maintaining documentation nobody kept current. Reviews deviations for about forty minutes a month instead.</p></div>
    <div class="card"><h3>The principal engineer</h3><p>Reads what the system learned from his own sessions, in text, and corrects it. Gets interrupted less for things he has already explained.</p></div>
  </div>
</div></section>

<section class="alt"><div class="w narrow">
  <span class="eyebrow">What you actually get</span>
  <h2>A library, not a chatbot.</h2>
  <ul class="big">
    <li>A <strong>skill library per client environment</strong> &mdash; readable text your engineers own, correct and can reject.</li>
    <li>A <strong>runbook that stays true</strong>, because it is maintained by observation rather than by discipline.</li>
    <li>A <strong>tier-1 floor</strong> at clients nobody on the desk knows yet.</li>
    <li><strong>Knowledge that survives attrition</strong> for every procedure that was performed while capture was running.</li>
  </ul>
</div></section>

<section><div class="w narrow">
  <span class="eyebrow">Why you should believe it &mdash; and where it does not hold</span>
  <h2>The first environment costs you more, not less. We do not charge for it.</h2>
  <p>Week one is a normal onboarding: your engineers map the tenant exactly as they always have. The product removes none of that and then adds review work. <strong>Environment one runs 31&ndash;46 hours against a 25&ndash;40 baseline</strong> &mdash; worse. Compression begins at the second client, at 18&ndash;28 hours, which is why environment one is free.</p>
  <p>And on tickets we are not cheaper either. The work we automate is the cheapest quartile of your queue, which a junior technician clears for roughly $2&ndash;6. At $6 a resolved ticket we sit at or above your own marginal cost. <strong>What we sell there is throughput at a capacity ceiling</strong>, not savings.</p>
  <div class="rule warn"><strong>Every figure on this page is a declared target.</strong> There is no pilot and no customer. The pack states the number that would falsify the whole thing &mdash; skills synthesised in one environment executing correctly in another, below 50% &mdash; and commits to publishing it either way.</div>
</div></section>

<section class="cta"><div class="w narrow">
  <h2>Read the argument, including the parts against it.</h2>
  <p>Seventy documents: the research, the market arithmetic corrected three times in public, the architecture, and an audit that states what is still open.</p>
  <a class="btn lg" href="pack.html">Read the pack</a>
</div></section>` },

  { slug: 'product', title: 'Product — Understudy', desc: 'The closed loop: watch, distil, rehearse, gate, act, verify, learn.',
    next: [{ href: 'evidence.html', k: 'Evidence', t: 'What we know', d: 'And what is still untested.' },
           { href: 'pricing.html', k: 'Pricing', t: 'What it costs', d: 'Including the gap between what we charge and what hours justify.' }],
    body: `
<section class="page-head"><div class="w narrow"><span class="eyebrow">Product</span>
  <h1>A closed loop, and the link that makes it different from RPA.</h1>
  <p class="lede">Every part of this exists somewhere already. What does not exist anywhere is the circuit &mdash; capture that keeps failures, feeding clustering that keeps variance, producing skills that declare success, so that verification is possible, so that recovery is possible.</p></div></section>
<section><div class="w narrow">
  <h2>The loop</h2>
  <ol class="steps">
    <li><strong>Watch</strong> &mdash; screen, actions and optional narration across the admin surfaces engineers actually use. Failed and abandoned sessions are kept deliberately: they contain what successful runs never do.</li>
    <li><strong>Distil</strong> &mdash; recordings of the same procedure cluster into one skill, with the <em>distribution</em> of how it differs across environments kept alongside it.</li>
    <li><strong>Rehearse</strong> &mdash; the skill runs against live tickets without acting, and its intended actions are compared with what your engineer actually did.</li>
    <li><strong>Gate</strong> &mdash; every step is classified by blast radius. Destructive is always gated. Bulk reads are gated too, because a read that copies client data is an exfiltration surface regardless of its verb.</li>
    <li><strong>Act</strong> &mdash; under the agent&rsquo;s own directory identity, so your client&rsquo;s audit log attributes it without our help.</li>
    <li><strong>Verify</strong> &mdash; every action ends by testing the criterion the skill declared. When the interface changes, that criterion is still valid, so a break becomes a search rather than a failure.</li>
  </ol>
  <h2>Why this is not RPA, stated narrowly</h2>
  <p>RPA can assert on world state, and modern selector engines already recover from broken selectors through fuzzy, anchor and image fallbacks. Anyone who tells you otherwise gets corrected in the room. <strong>The real difference is that the goal is not carried in the RPA artifact in a form the runtime can re-plan against</strong> &mdash; so recovery is confined to fallbacks a developer wrote in advance. A skill carries the goal as a predicate held at execution time, so it can search a space nobody anticipated.</p>
  <div class="rule"><strong>And it is tested, not asserted.</strong> Against a fallback-enabled baseline built by a contracted certified practitioner and published for replication &mdash; because a baseline with its fallbacks switched off would prove nothing.</div>
  <h2>Where your recordings live</h2>
  <p>Clustering runs inside your own tenant. <strong>Raw session recordings never reach us.</strong> The only thing that crosses is an abstracted pattern &mdash; the shape of a procedure and how it varies &mdash; and only once the same pattern has been seen at three or more separate MSPs. A pattern seen once is a fingerprint, so it does not travel.</p>
</div></section>` },

  { slug: 'evidence', title: 'Evidence — Understudy', desc: 'What is sourced, what is assumed, and what is untested.',
    next: [{ href: 'pricing.html', k: 'Pricing', t: 'What it costs', d: 'And what the hours justify.' },
           { href: 'pack.html', k: 'The pack', t: 'All 70 documents', d: 'Including the audit of what is missing.' }],
    body: `
<section class="page-head"><div class="w narrow"><span class="eyebrow">Evidence</span>
  <h1>There is no traction. Here is exactly what we do and do not know.</h1>
  <p class="lede">No pilot, no customer, no code. This page exists because a pack that hides that would not be worth reading.</p></div></section>
<section><div class="w">
  <h2>Sourced</h2>
  <table class="ev">
    <tr><td>Onboarding a median client costs 25&ndash;40 engineer-hours</td><td class="src">[S21], banded</td></tr>
    <tr><td>26% of MSPs cannot staff clients they could win</td><td class="src">[S33]</td></tr>
    <tr><td>Computer-use agents: 12% (Apr 2024) &rarr; ~86% on OSWorld</td><td class="src">[S14][S15]</td></tr>
    <tr><td><strong>Those same agents fail ~80% of real workflows; long-horizon completion is 20.6%</strong></td><td class="src">[S15][S16]</td></tr>
    <tr><td>RPA: 30&ndash;50% of projects fail; maintenance reaches 60% of cost</td><td class="src">[S10][S11]</td></tr>
    <tr><td>ServiceNow implementation runs 3&ndash;5&times; the annual licence</td><td class="src">[S20]</td></tr>
  </table>
  <h2>Assumed, and tagged as such</h2>
  <p>The endpoint-to-user ratio behind the market model. The share of an MSP queue that is automatable. The hours a median client actually takes. The cost of the tickets we address. Each carries an <code>(assumption)</code> tag in the pack and names the experiment that would settle it.</p>
  <h2>Unknown, and stated</h2>
  <ul class="big">
    <li><strong>Whether skills transfer between environments at all.</strong> No benchmark exists, no prior system has published one, and it is the assumption the company rests on.</li>
    <li>Whether an MSP owner pays for a library, or only for the hours it saves.</li>
    <li>Whether a vendor founder can even join the channels this plan depends on.</li>
    <li>Whether an abstracted pattern can be traced back to the tenant it came from.</li>
  </ul>
  <div class="rule warn"><strong>Four of those five would end the company, and three of them cost under $10,000 to test.</strong> None needs code. That is the sequencing argument, and it is why the round is sized to fund a question rather than a company.</div>
</div></section>` },

  { slug: 'pricing', title: 'Pricing — Understudy', desc: 'Two parts, first environment free, and the gap between what we charge and what hours justify.',
    next: [{ href: 'about.html', k: 'About', t: 'Who is building it', d: 'Including the gap in the team.' },
           { href: 'pack.html', k: 'The pack', t: 'The full model', d: 'Every figure, with its source or its tag.' }],
    body: `
<section class="page-head"><div class="w narrow"><span class="eyebrow">Pricing</span>
  <h1>Two parts. The first environment is free, because it costs you more than doing nothing.</h1></div></section>
<section><div class="w narrow">
  <table class="ev">
    <tr><td><strong>Per environment onboarded</strong>, from the second<br><span class="d">banded by client size</span></td><td class="k">$400 &middot; $1,500 &middot; $1,500</td></tr>
    <tr><td><strong>Per resolved ticket</strong><br><span class="d">verified, and not reversed within the ticket</span></td><td class="k">~$6</td></tr>
    <tr><td><strong>Environment one</strong></td><td class="k sig">free</td></tr>
  </table>
  <h2>The gap we are not hiding</h2>
  <p>Priced against the engineer-hours it displaces, that schedule does not hold. A consistent calculation puts the fee at <strong>99&ndash;466% of the hours saved</strong>, depending on client size &mdash; above the value at every band. An hours-defensible schedule would blend to about <strong>$246</strong> rather than $1,005.</p>
  <p>We publish both because the question is genuinely open: <strong>is the library worth paying for on its own, or only worth the hours it saves?</strong> Ten conversations with MSP owners settle that, and no amount of modelling can. Until they happen, both numbers stand on this page.</p>
  <div class="rule"><strong>One thing to plan for:</strong> the distillation node runs in your tenant, so raw recordings never leave your control. Hosted, that is roughly $150&ndash;250 a month &mdash; which we state here rather than in a later invoice.</div>
</div></section>` },

  { slug: 'visuals', title: 'Visuals — Understudy', desc: 'Twenty infographics built from the pack: the market build, the risk matrix, the pricing bands, the journeys and the experiment board.',
    next: [{ href: 'pack.html', k: 'The pack', t: 'All 70 documents', d: 'The arguments these figures come from.' },
           { href: 'evidence.html', k: 'Evidence', t: 'What we know', d: 'Sourced, assumed and unknown.' }],
    body: `
<section class="page-head"><div class="w"><span class="eyebrow">Visuals</span>
  <h1>Twenty figures, every number traced to a document.</h1>
  <p class="lede">Each of these is generated from a specific artifact in the pack and cites it at the foot of the page. They are HTML rather than images on purpose: the tables carry numbers a reader needs to be able to copy and check, and that is exactly what image models garble.</p></div></section>
<section><div class="w"><div class="vgrid">
<a class="vcard" href="visuals/infographics/V02_positioning-map.html"><span class="ve">Positioning · V02</span><h3>Three quadrants are crowded. The fourth was empty for a reason that expired in 2024.</h3><p>The axes were discovered from the competitor teardown, not chosen from a template. Price × quality is not the map here — what divides this market is how a system acquires environment knowled…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V09_sam-build.html"><span class="ve">Market sizing · V09</span><h3>A defended $179M SAM, built bottom-up and corrected three times.</h3><p>Every factor is sourced or flagged. The two softest numbers are named as such, and the sensitivity band is shown rather than a point estimate.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V10_evidence-ledger.html"><span class="ve">What we know · V10</span><h3>Every company-killing assumption is untested, and three of four cost under $2,000 to test.</h3><p>This is the honest state of a pre-build company. Stating it in one table is more useful than distributing the same fact across sixty artifacts.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V11_hours-per-environment.html"><span class="ve">The number the GTM rests on · V11</span><h3>The first environment costs more, not less. We do not charge for it.</h3><p>A design partner's timesheet should confirm this chart, not falsify it. Compression begins at environment 2, and environment 1 is waived because charging for it would be charging for a loss.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V14_use-of-funds.html"><span class="ve">The raise · V14</span><h3>0.5% of the round can invalidate the other 99.5%. It is spent first.</h3><p>Ordered by cost, not importance. Four of five company-killing assumptions retire for under $10,000; the fifth is the company.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V15_risk-matrix.html"><span class="ve">Residual risk · V15</span><h3>Four residuals stay high, and one has no mitigation at all.</h3><p>A matrix where everything mitigates to low is fiction. This is the correct shape for a pre-build company with one unmeasured mechanism, a solo founder and a ceiling on its market.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V16_revenue-quality.html"><span class="ve">Revenue build · V16</span><h3>73% of three-year revenue is one-time. Say it before diligence computes it.</h3><p>During the land phase this is implementation-shaped revenue earning a services multiple — the same revenue quality this pack criticises ServiceNow for. The difference is that ours decays by …</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V18_banded-pricing.html"><span class="ve">Pricing · V18</span><h3>What we charge, beside what the hours justify.</h3><p>One consistent method across all three bands: matched pairs, at the $46–58/hr the file's own $95–120k loaded technician implies. The gap is shown deliberately — E3 is the test that resolves …</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V19_decision-unit.html"><span class="ve">Who can say no · V19</span><h3>A deal signed by the owner can still fail three times over.</h3><p>Personas cover who benefits. This covers who can stop it — and two of the vetoes sit outside the reporting line, both concerning the recording rather than the product.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V20_journey-edge-low.html"><span class="ve">Edge-low journey · V20</span><h3>A tier-1 technician resolves a ticket at a client she has never touched.</h3><p>The component acting is named at every beat. A skeptic should be able to reconstruct the sequence without reading the prose.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V21_journey-beachhead.html"><span class="ve">Beachhead journey · V21</span><h3>Onboarding one environment: week 1 produces nothing, and that is the honest part.</h3><p>This is the journey the entire go-to-market is priced against. All figures are illustrative targets — no pilot exists.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V22_journey-edge-high.html"><span class="ve">Edge-high journey · V22</span><h3>The persona who can veto adoption without attending a meeting.</h3><p>Ray is both the highest-value source of skills and the person best equipped to reject the system. Beats 1–4 are conversion; 5–8 are the stretch.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V23_day-in-life.html"><span class="ve">Day in the life · V23</span><h3>Four seats, one day, and an incident no verification step could have caught.</h3><p>Ticket volume derived rather than asserted: ~620 users × 0.8/month ≈ 496 tickets across the book, ~8 of 20 staff on queue, ~3/day each, Tuesday running double.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V24_thirteen-screens.html"><span class="ve">UX specification · V24</span><h3>Two screens decide adoption, and neither is a dashboard.</h3><p>This product asks people to be recorded and asks a sceptical expert to endorse what was learned from them. Those are interface problems before they are model problems.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V25_feature-tiers.html"><span class="ve">Build plan · V25</span><h3>The Now tier is the whole bet, and its floor is ~40 weeks for one person.</h3><p>Priority is risk-ordered, not chronological. The earliest items retire the assumption that kills the company, not the ones a user sees first.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V26_technique-matrix.html"><span class="ve">Tech · V26</span><h3>Two orphan techniques turned out to be missing safety features.</h3><p>A catalogue and a feature list can both look complete while being disconnected. The two failure columns are the point.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V28_experiment-board.html"><span class="ve">Validation · V28</span><h3>Eight experiments, every threshold declared before any data exists.</h3><p>Thresholds declared after results are not thresholds. Order is by cost, not importance — four of these need no product at all.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V29_stage-gate.html"><span class="ve">Where we are · V29</span><h3>Customer Discovery, early. Not Validation — and the placement is argued against our interest.</h3><p>A founder under pressure describes the company one stage ahead of where it is, which causes money and hiring to be spent on the wrong stage.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V30_metrics-by-stage.html"><span class="ve">What to track · V30</span><h3>The vanity metrics here are unusually seductive.</h3><p>A capture product generates impressive volume numbers from day one that are entirely uncorrelated with whether it works.…</p><span class="vgo">Open →</span></a>
<a class="vcard" href="visuals/infographics/V31_pivot-log.html"><span class="ve">What has been killed · V31</span><h3>Five load-bearing claims survived authorship and did not survive scrutiny.</h3><p>A company that cannot say what it has already rejected has not made any decisions. The entries produced by adversarial review are the most useful ones here.…</p><span class="vgo">Open →</span></a>
</div>
<p class="hint" style="margin-top:34px;color:#8A8A99;font-size:13.5px">A further 46 figures exist as production-ready image prompts in <code>visuals/image_prompts.md</code>. They are unrendered — this run had no text-to-image tool, and <code>audit/COVERAGE.md</code> records that as an open row rather than closing it.</p>
</div></section>` },

  { slug: 'about', title: 'About — Understudy', desc: 'Why this problem, what is missing from the team, and what would make us stop.',
    next: [{ href: 'pack.html', k: 'The pack', t: 'All 70 documents', d: 'The full argument and the audit.' },
           { href: 'evidence.html', k: 'Evidence', t: 'What we know', d: 'Sourced, assumed and unknown.' }],
    body: `
<section class="page-head"><div class="w narrow"><span class="eyebrow">About</span>
  <h1>Why this problem, and what is missing.</h1></div></section>
<section><div class="w narrow">
  <h2>Why now</h2>
  <p>Agents crossed a threshold in the last eighteen months: they can follow a multi-step workflow in a real interface and recover from a wrong click. That is the capability that turns a recording into something executable, and it did not exist in 2023. At the same time <code>SKILL.md</code> became an open format adopted across more than twenty platforms &mdash; so a distilled procedure finally has somewhere to live that is not a fine-tuned model.</p>
  <p>This was tried before. A company called FortressIQ was recording employees with computer vision from 2017 and was acquired into an automation vendor in 2021. Right input, wrong decade: there was nothing to send the recording to.</p>
  <h2>The gap in the team, named</h2>
  <p>The founder&rsquo;s background is AI and agent engineering. The clustering problem &mdash; turning many messy recordings into one reliable skill &mdash; is the hard bet in this company and it is the founder&rsquo;s ground.</p>
  <p><strong>There is no managed-services operating history here.</strong> Nobody on this side has run an MSP or felt the 2am onboarding before a Monday contract start. That is why the plan begins with ten conversations and no product pitch, why the first hire is an MSP-side operator rather than an engineer, and why design partners are asked for their timesheets rather than their enthusiasm.</p>
  <h2>What would make us stop</h2>
  <p>If skills synthesised in one environment execute correctly in another less than half the time, after three genuine attempts at the method, the core claim is false. <strong>We would publish that.</strong> The field has assumed this works for forty years without measuring it, and a clean negative result is the most useful thing we could contribute if the positive one does not arrive.</p>
</div></section>` },
];

let n = 0;
for (const page of PAGES) { fs.writeFileSync(`${page.slug}.html`, shell(page)); n++; }
console.log(`built ${n} pages: ${PAGES.map(p => p.slug + '.html').join(', ')}`);

// Verify: walk every href/src in the generated pages and assert the target exists.
// Exclude pack.html — template literals in its embedded script look like links.
let bad = 0, checked = 0;
for (const page of PAGES) {
  const s = fs.readFileSync(`${page.slug}.html`, 'utf8');
  for (const m of s.matchAll(/(?:href|src)="([^"#][^"]*?)"/g)) {
    const t = m[1].split('#')[0];
    if (!t || /^(https?:|data:|mailto:)/.test(t)) continue;
    checked++;
    if (!fs.existsSync(t)) { console.log(`  BROKEN ${page.slug}.html -> ${t}`); bad++; }
  }
}
console.log(`${checked} local refs checked, ${bad} broken`);
